
trigger:
  - main

pool:
    vmImage: ubuntu-latest
  
stages:
  - stage: Terraform_Config
    displayName: Terraform Install, init and plan
    jobs:
      - job: Deploy 
        steps:
          - task: TerraformInstaller@0
            inputs:
               terraformVersion: '0.14.6'
  
          - task: TerraformTaskV2@2
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              commandOptions: '-backend-config="backend_config/resources.tfvars" -reconfigure'
              backendServiceArm: ''
              backendAzureRmResourceGroupName: ''
              backendAzureRmStorageAccountName: ''
              backendAzureRmContainerName: ''
              backendAzureRmKey: ''
          
          - task: TerraformTaskV2@2
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          
          - task: TerraformTaskV2@2
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              environmentServiceNameAzureRM: ''
              
              
          - task: TerraformTaskV2@2
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              environmentServiceNameAzureRM: ''

